language: perl
services:
    - mysql
    - postgresql
perl:
    - "5.22"
    - "5.24"
before_script:
    - psql -c 'create database objectdb;' -U postgres
before_install:
    - cpanm -n https://github.com/kritikaio/devel-cover-report-kritika-perl/archive/master.tar.gz
install:
    - cpanm -n -q --with-recommends --skip-satisfied --installdeps .
    - cpanm -n -q DBD::SQLite DBD::Pg DBD::mysql
script:
    - TEST_OBJECTDB_DBH=dbi:Pg:dbname=objectdb prove -Ilib -r t
    - TEST_OBJECTDB_DBH=dbi:mysql:database=travis prove -Ilib -r t
    - perl Build.PL && ./Build build && cover -test -report kritika
